version : '3'
services:
    neodb:
        image: 'neo4j'
        environment:
            - NEO4J_AUTH=neo4j/pass123456
            - NEO4J_dbms_security_procedures_unrestricted=algo.*
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - ./neo4j/data:/data
            - ./neo4j/logs:/logs
            - ./neo4j/import:/var/lib/neo4j/import
            - ./neo4j/plugins:/plugins
    pgdb:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_USER=pg
            - POSTGRES_PASSWORD=pass123456
            - POSTGRES_DB=stocks
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgresql/data
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        env_file: 
            - vars.env
        tty: True
        depends_on:
            - neodb
            - pgdb